#!/bin/sh
set -e

L2T_CONF="/etc/locast2tuner/config.ini"

case "$1" in
purge)
    # Per https://www.debian.org/doc/debian-policy/ch-files.html#behavior
    # "configuration files must be preserved when the package is removed, and
    #  only deleted when the package is purged."
    if [ -f ${L2T_CONF} ]; then
        rm ${L2T_CONF}
    fi
    ;;
esac

#DEBHELPER#
